site_name: CrIS Code Collection
site_url: https://slcs-jsc.github.io/cris/
repo_url: https://github.com/slcs-jsc/cris
docs_dir: manual
theme: material

nav:
    - Home: index.md
    - Links: links.md
